### PR TITLE
Add code list catalogue

### PR DESCRIPTION
**Pull request by fmcgrath**

### CODE REVIEW

**Review by coolkrish04 — DISMISSED** [review]
good to go for QA. Please share the QA TIS link to review as html file.

**Comment by fmcgrath** [comment]
@coolkrish04 - I had to update issued date to today. You will need to reapprove the PR. Thanks.

**Review by coolkrish04 — APPROVED** [review]
Good to go!

**Comment by cariadkeith** [comment]
Branch merged 10:30 am Dec 15 2023

**Comment by cariadkeith** [comment]
Merge for release

**Pull request merged**
