### PR TITLE
CTCP-1075 Added hr under version in index

### PR DESCRIPTION
**Pull request by crystalmark**

### CODE REVIEW

**Review by PeterBandura — DISMISSED** [review]

**Review by fmcgrath — APPROVED** [review]
Looks OK.

**Review by PeterBandura — APPROVED** [review]

**Review by fmcgrath — COMMENTED** [review]
Changes for IE013 look OK. However, I am not sure that comment "The rule C0250 is also missing." was implemented for IE017.

**Comment by fmcgrath** [comment]
> Changes for IE013 look OK. However, I am not sure that comment "The rule C0250 is also missing." was implemented for IE017.

@crystalmark - After Slack discussion with Kirshna, it seems that Nipul withdrew his request for adding rule C0250 to IE017. Krishna has double-checked changes to `.md` files against DDNTA and is happy that all required changes have been implemented. Therefore, I now have no concerns about this PR.

**Comment by coolkrish04** [comment]
I have double checked your concern with Nipul.  

**House Consignment > Consignor > Address data** field must not contain any rules associated. So our implementation is right and it is as per DDNTA.

**Pull request merged**
